name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
    tags: '*'

jobs:
  runtimes-build-and-test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        run: |
          BRANCH_OR_TAG=${GITHUB_REF#refs/heads/}
          BRANCH_OR_TAG=${BRANCH_OR_TAG#refs/tags/}
          git clone --single-branch --branch $BRANCH_OR_TAG --depth 1 https://${{ secrets.CLONE_TOKEN }}:x-oauth-basic@github.com/${{ github.repository }}.git .
      - name: cleanup
        run: sudo rm -rf "/usr/local/share/boost" "$AGENT_TOOLSDIRECTORY"
      - name: Build runtimes
        run: make build
      - name: Run tests
        run: make testv
